### ISSUE TITLE
Implementation not working when Kubernetes cluster is behind proxy

### ISSUE THREAD

**Issue by kpn-mcs** [sysdiglabs/harbor-scanner-sysdig-secure#5]
When the Kubernetes cluster is behind a proxy with authentication the current connector does not work. External connection to the sysdig SaaS API needs to be routed through a proxy. This can be achieved by adding the proxy to the pod env variables.

**Comment by airadier** [comment]
Support for proxy is being added in PR #7, by setting http_proxy and https_proxy environment variables.
